/*
@TargetNode='localhost'
@GeneratedBy=Mikey
@GenerationDate=11/06/2021 11:38:19
@GenerationHost=FUFA
*/

instance of MSFT_FileDirectoryConfiguration as $MSFT_FileDirectoryConfiguration1ref
{
ModuleName = "PSDesiredStateConfiguration";
 Ensure = "Present";
 SourceInfo = "C:\\Users\\micha\\OneDrive\\SQL\\Presentation\\Dataweekender\\2021_4.2\\01_dsc\\dsc_config.ps1::9::9::file";
 Type = "Directory";
 ResourceID = "[File]dscDemoDir";
 DestinationPath = "C:\\dscDemoDir\\";

ModuleVersion = "1.0";
 ConfigurationName = "dscDemo";
};
instance of MSFT_FileDirectoryConfiguration as $MSFT_FileDirectoryConfiguration2ref
{
ModuleName = "PSDesiredStateConfiguration";
 Ensure = "Present";
 SourceInfo = "C:\\Users\\micha\\OneDrive\\SQL\\Presentation\\Dataweekender\\2021_4.2\\01_dsc\\dsc_config.ps1::15::9::file";
 Type = "File";
 ResourceID = "[File]dscDemoFile";
 Contents = "This is a text in dscDemoFile file in dscDemoDir folder on localhost";
 DestinationPath = "C:\\dscDemoDir\\dscDemoFile.txt";

ModuleVersion = "1.0";
DependsOn = {
    "[File]dscDemoDir"};
 ConfigurationName = "dscDemo";
};
instance of OMI_ConfigurationDocument

                    {
 Version="2.0.0";

                        MinimumCompatibleVersion = "1.0.0";

                        CompatibleVersionAdditionalProperties= {"Omi_BaseResource:ConfigurationName"};

                        Author="Mikey";

                        GenerationDate="11/06/2021 11:38:19";

                        GenerationHost="FUFA";

                        Name="dscDemo";

                    };
